<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script>
var myval = 123; // generated by PHP
$.ajax({
  type: 'POST',
  url: '../db/compareSymptoms.php',
  data: {'variable': myval},
});
</script>
<?php
var myval = foo("this is a php variable"); // generated by PHP2
echo "var myval = foo(" . parameter . ");";
?>
</head>
<body>
</body>
</html>